In [1]:
import pandas as pd

kote = pd.read_csv('data/kote_relabeled.csv')
aihub = pd.read_csv('data/aihub_relabeled.csv')

In [5]:
print(kote.head())
print(aihub.head())

   Unnamed: 0     ID                                               text  \
0           0  39087              내가 톰행크스를 좋아하긴 했나보다... 초기 영화 빼고는 다 봤네.
1           1  30893  정말 상상을 초월하는 무개념 진상들 상대하다 우울증, 공항장애 걸리는 공무원 많아요...
2           2  45278  새로운 세상과 조우한 자의 어린아이 같은 반응, 어쩌면 회복된 것은 눈이 아닌 순수...
3           3  16398       미역은 원생생물계 산호초는 동물ㅇㅇ 아 미역이 바다의 새ㄱㅇㄱㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
4           4  13653                        네 맞습니다 플스는 역시 30프레임이 어울리죠 ㅎ

                                     labels final_label
0                       [ 2 13 15 16 29 39]          긍정
1           [ 0  5  7 10 19 22 29 35 36 38]          부정
2                                   [1 2 7]          긍정
3                    [ 9 15 20 23 26 28 29]          긍정
4  [ 1  2  8  9 11 13 15 16 28 29 32 40 42]          긍정
                   Sentence Emotion Label
0  언니 동생으로 부르는게 맞는 일인가요..??      공포    중립
1              그냥 내 느낌일뿐겠지?      공포    중립
2            아직너무초기라서 그런거죠?      공포    중립
3             유치원버스 사고 낫다던데      공포    중립
4               근데 원래이런거맞나요      공포    중립

In [7]:
kote = kote[['text', 'final_label']]
kote = kote.rename(columns={'text': 'Text', 'final_label': 'Completion'})
kote

                                                    Text Completion
0                  내가 톰행크스를 좋아하긴 했나보다... 초기 영화 빼고는 다 봤네.         긍정
1      정말 상상을 초월하는 무개념 진상들 상대하다 우울증, 공항장애 걸리는 공무원 많아요...         부정
2      새로운 세상과 조우한 자의 어린아이 같은 반응, 어쩌면 회복된 것은 눈이 아닌 순수...         긍정
3           미역은 원생생물계 산호초는 동물ㅇㅇ 아 미역이 바다의 새ㄱㅇㄱㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ         긍정
4                            네 맞습니다 플스는 역시 30프레임이 어울리죠 ㅎ         긍정
...                                                  ...        ...
49995  일단 내용만 보고놓자면 크게 신경쓸일은 아닌거같네요 한국룸메랑 같이 비교하지마세요 ...         긍정
49996  캐릭터가 프린트된 제품인줄 알았는데 스티커임 손으로 조물조물 빨았는데 캐릭터들이 쪼...         부정
49997                          마지막에 마카롱으로 미키마우스만든거 넘귀엽다ㅋ         긍정
49998                    너무 멋진 친구를 두셨네요  작가님 함께 같이 살아갑시다         긍정
49999                          강려크하시니 오늘은 검색하지 않겟습니다. ㅋㅋ         긍정

[50000 rows x 2 columns]

In [16]:
kote = kote[['Text', 'Completion']]
kote.to_csv('kote.csv', index=False)

In [8]:
aihub = aihub[['Sentence', 'Label']]
aihub = aihub.rename(columns={'Sentence': 'Text', 'Label': 'Completion'})
aihub

                                                    Text Completion
0                               언니 동생으로 부르는게 맞는 일인가요..??         중립
1                                           그냥 내 느낌일뿐겠지?         중립
2                                         아직너무초기라서 그런거죠?         중립
3                                          유치원버스 사고 낫다던데         중립
4                                            근데 원래이런거맞나요         중립
...                                                  ...        ...
38589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..         부정
38590                                        재미가 없으니 망하지         부정
38591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...         부정
38592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ         부정
38593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요         부정

[38594 rows x 2 columns]

### kote + aihub

In [9]:
df = pd.concat([kote, aihub], ignore_index=True)
df

                                                    Text Completion
0                  내가 톰행크스를 좋아하긴 했나보다... 초기 영화 빼고는 다 봤네.         긍정
1      정말 상상을 초월하는 무개념 진상들 상대하다 우울증, 공항장애 걸리는 공무원 많아요...         부정
2      새로운 세상과 조우한 자의 어린아이 같은 반응, 어쩌면 회복된 것은 눈이 아닌 순수...         긍정
3           미역은 원생생물계 산호초는 동물ㅇㅇ 아 미역이 바다의 새ㄱㅇㄱㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ         긍정
4                            네 맞습니다 플스는 역시 30프레임이 어울리죠 ㅎ         긍정
...                                                  ...        ...
88589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..         부정
88590                                        재미가 없으니 망하지         부정
88591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...         부정
88592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ         부정
88593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요         부정

[88594 rows x 2 columns]

In [10]:
print(len(df[df['Completion']=='긍정']))
print(len(df[df['Completion']=='부정']))
print(len(df[df['Completion']=='중립']))

28579
36266
23749

In [11]:
# '긍정'과 '부정' 라벨을 25000개로 다운샘플링
df_positive_downsampled = df[df['Completion'] == '긍정'].sample(n=25000, random_state=42)
df_negative_downsampled = df[df['Completion'] == '부정'].sample(n=25000, random_state=42)
df_neutral = df[df['Completion'] == '중립']

# 다운샘플링된 데이터프레임들을 결합
downsampled_df = pd.concat([df_positive_downsampled, df_negative_downsampled, df_neutral])

downsampled_df = downsampled_df.sample(frac=1, random_state=42).reset_index(drop=True)
downsampled_df.to_csv('downsampled_three_emotions.csv', index=False)

In [12]:
print(len(downsampled_df[downsampled_df['Completion']=='긍정']))
print(len(downsampled_df[downsampled_df['Completion']=='부정']))
print(len(downsampled_df[downsampled_df['Completion']=='중립']))

25000
25000
23749

In [17]:
# 샘플링된 인덱스 저장
positive_sampled_indices = df_positive_downsampled.index
negative_sampled_indices = df_negative_downsampled.index

# 남은 데이터에서 추가로 3500개 샘플링
remaining_positive = df[df['Completion'] == '긍정'].drop(positive_sampled_indices)
remaining_negative = df[df['Completion'] == '부정'].drop(negative_sampled_indices)

additional_positive = remaining_positive.sample(n=3500, random_state=42)
additional_negative = remaining_negative.sample(n=3500, random_state=42)

# 추가 샘플링된 데이터를 CSV로 저장
additional_samples = pd.concat([additional_positive, additional_negative])
additional_samples = additional_samples.sample(frac=1, random_state=42).reset_index(drop=True)
additional_samples.to_csv('test_three_emotions.csv', index=False)

In [18]:
additional_samples

                                                   Text Completion
0     베이지 구매했는데 레드가 배송되어왔습니다 상자표면에 레드라 써있었는데 좀 더 신경써...         부정
1                 또 신차가있어요? 더 뉴 렉스턴 스포츠 칸 이후로 또나온건가요 그럼         긍정
2                                           진짜 너무 멋지심ㅋㅋ         긍정
3                            울동원이    이대로잇음좋켓어요 넘넘예뻐용 !!         긍정
4                  위증 위증교사 짜고치는 한패 다 법의심판을 받길....!!!!!!         부정
...                                                 ...        ...
6995             Ocn으로 봤는데... 와 이걸 돈주고 본 사람은 정말 억울했겠네요.         부정
6996                                         와... 대박...         부정
6997  나라를 지키는 국군 장병에게 부당한처우를하지말라.개인의 자유도 빼앗긴채 나라를 지키...         부정
6998                              위증을 하는자는 중벌로 다스려야 합니다         부정
6999  그러나 어떤 이는 아름다운 기억을 품고 살아갑니다. 누구에게나 똑같이 주어지는 기쁨...         긍정

[7000 rows x 2 columns]